version: '3.8'

services:
  # Reverse Proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.0
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
    networks:
      - app-network

  acme-companion:
    image: nginxproxy/acme-companion:2.2
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
    networks:
      - app-network

  # Services
  storage-node:
    container_name: storage-node
    restart: always
    build:
      context: .
      dockerfile: storage-node/Dockerfile
    depends_on:
      - sequencer
    networks:
      - app-network
    environment:
      - PORT=3001
      - SEQUENCER_URL=http://sequencer-node:3000
      - NODE_SK=
      - VIRTUAL_HOST=node.ss.testnet.zeropool.network
      - LETSENCRYPT_HOST=node.ss.testnet.zeropool.network
      - LETSENCRYPT_EMAIL=mail@test.com
    volumes:
      - node_data:/app/storage-node/data

  sequencer:
    container_name: sequencer
    restart: always
    build:
      context: .
      dockerfile: sequencer/Dockerfile
    networks:
      - app-network
    environment:
      - PORT=3000
      - OPERATOR_SK=
      - RPC_UR=
      - MASTER_SK=
      - ROLLUP_CONTRACT_ADDRESS=
      - MOCK_BLOCKCHAIN=false
      - VIRTUAL_HOST=sequencer.ss.testnet.zeropool.network
      - LETSENCRYPT_HOST=sequencer.ss.testnet.zeropool.network
      - LETSENCRYPT_EMAIL=mail@test.com
    volumes:
      - sequencer_data:/app/sequencer/data

  client-app:
    container_name: client-app
    depends_on:
      - storage-node
      - sequencer
    restart: always
    build:
      context: .
      dockerfile: client-app/Dockerfile
      args:
        - PUBLIC_SEQUENCER_API_URL=https://sequencer.ss.testnet.zeropool.network/
        - PUBLIC_NODE_API_URL=https://node.ss.testnet.zeropool.network/
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=ss.testnet.zeropool.network
      - LETSENCRYPT_HOST=ss.testnet.zeropool.network
      - LETSENCRYPT_EMAIL=mail@test.com

volumes:
  vhost:
  html:
  certs:
  acme:
  conf:
  files:
  sequencer_data:
  node_data:


networks:
  app-network:
    driver: bridge
