pubhash = ""

[[input.file.txs]]

[input.file.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.file.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.file.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.file.txs.tx]
data = ""
data_index = ""
nonce = ""
sender_index = ""
time_interval = ""

[[input.file.txs]]

[input.file.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.file.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.file.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.file.txs.tx]
data = ""
data_index = ""
nonce = ""
sender_index = ""
time_interval = ""

[[input.file.txs]]

[input.file.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.file.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.file.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.file.txs.tx]
data = ""
data_index = ""
nonce = ""
sender_index = ""
time_interval = ""

[[input.file.txs]]

[input.file.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.file.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.file.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.file.txs.tx]
data = ""
data_index = ""
nonce = ""
sender_index = ""
time_interval = ""

[[input.file.txs]]

[input.file.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.file.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.file.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.file.txs.tx]
data = ""
data_index = ""
nonce = ""
sender_index = ""
time_interval = ""

[[input.file.txs]]

[input.file.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.file.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.file.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.file.txs.tx]
data = ""
data_index = ""
nonce = ""
sender_index = ""
time_interval = ""

[[input.file.txs]]

[input.file.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.file.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.file.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.file.txs.tx]
data = ""
data_index = ""
nonce = ""
sender_index = ""
time_interval = ""

[[input.file.txs]]

[input.file.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.file.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.file.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.file.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.file.txs.tx]
data = ""
data_index = ""
nonce = ""
sender_index = ""
time_interval = ""

[[input.mining.txs]]

[input.mining.txs.assets]
data_in_file = ""
random_oracle_value = ""

[input.mining.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.mining.txs.assets.file]
data = ""
expiration_time = ""
owner = ""

[input.mining.txs.assets.proof_data_in_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.mining.txs.assets.proof_file]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.mining.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.mining.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.mining.txs.tx]
mining_nonce = ""
nonce = ""
random_oracle_nonce = ""
sender_index = ""

[input.new_root]
acc = ""
data = ""

[input.old_root]
acc = ""
data = ""

[input.public]
new_root = ""
now = ""
old_root = ""

[input.public.oracle]
data = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
offset = ""

[[input.tx.txs]]

[input.tx.txs.assets.account_receiver]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.proof_receiver]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.tx.txs.tx]
amount = ""
nonce = ""
receiver_index = ""
receiver_key = ""
sender_index = ""

[[input.tx.txs]]

[input.tx.txs.assets.account_receiver]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.proof_receiver]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.tx.txs.tx]
amount = ""
nonce = ""
receiver_index = ""
receiver_key = ""
sender_index = ""

[[input.tx.txs]]

[input.tx.txs.assets.account_receiver]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.proof_receiver]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.tx.txs.tx]
amount = ""
nonce = ""
receiver_index = ""
receiver_key = ""
sender_index = ""

[[input.tx.txs]]

[input.tx.txs.assets.account_receiver]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.proof_receiver]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.tx.txs.tx]
amount = ""
nonce = ""
receiver_index = ""
receiver_key = ""
sender_index = ""

[[input.tx.txs]]

[input.tx.txs.assets.account_receiver]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.proof_receiver]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.tx.txs.tx]
amount = ""
nonce = ""
receiver_index = ""
receiver_key = ""
sender_index = ""

[[input.tx.txs]]

[input.tx.txs.assets.account_receiver]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.proof_receiver]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.tx.txs.tx]
amount = ""
nonce = ""
receiver_index = ""
receiver_key = ""
sender_index = ""

[[input.tx.txs]]

[input.tx.txs.assets.account_receiver]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.proof_receiver]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.tx.txs.tx]
amount = ""
nonce = ""
receiver_index = ""
receiver_key = ""
sender_index = ""

[[input.tx.txs]]

[input.tx.txs.assets.account_receiver]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.account_sender]
balance = ""
key = ""
nonce = ""
random_oracle_nonce = ""

[input.tx.txs.assets.proof_receiver]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.proof_sender]
hash_path = ["", "", "", "", "", "", "", "", "", ""]
index_bits = ["", "", "", "", "", "", "", "", "", ""]

[input.tx.txs.assets.signature]
a = ""
r8 = ""
s = ""

[input.tx.txs.tx]
amount = ""
nonce = ""
receiver_index = ""
receiver_key = ""
sender_index = ""
